import pandas as pd
import numpy as np
import re
import csv

def findHouseNum(df, votes, x, y):
    if re.search("001", str(df.iloc[x,4])):
        votes[0] += int(df.iloc[x,12])
        y = 0
    if re.search("002", str(df.iloc[x,4])):
        votes[1] += int(df.iloc[x,12])
        y = 1
    if re.search("003", str(df.iloc[x,4])):
        votes[2] += int(df.iloc[x,12])
        y = 2
    if re.search("004", str(df.iloc[x,4])):
        votes[3] += int(df.iloc[x,12])
        y = 3
    if re.search("005", str(df.iloc[x,4])):
        votes[4] += int(df.iloc[x,12])
        y = 4
    if re.search("006", str(df.iloc[x,4])):
        votes[5] += int(df.iloc[x,12])
        y = 5
    if re.search("007", str(df.iloc[x,4])):
        votes[6] += int(df.iloc[x,12])
        y = 6
    if re.search("008", str(df.iloc[x,4])):
        votes[7] += int(df.iloc[x,12])
        y = 7
    if re.search("009", str(df.iloc[x,4])):
        votes[8] += int(df.iloc[x,12])
        y = 8
    if re.search("010", str(df.iloc[x,4])):
        votes[9] += int(df.iloc[x,12])
        y = 9
    if re.search("011", str(df.iloc[x,4])):
        votes[10] += int(df.iloc[x,12])
        y = 10
    if re.search("012", str(df.iloc[x,4])):
        votes[11] += int(df.iloc[x,12])
        y = 11
    if re.search("013", str(df.iloc[x,4])):
        votes[12] += int(df.iloc[x,12])
        y = 12
    if re.search("014", str(df.iloc[x,4])):
        votes[13] += int(df.iloc[x,12])
        y = 13
    if re.search("015", str(df.iloc[x,4])):
        votes[14] += int(df.iloc[x,12])
        y = 14
    if re.search("016", str(df.iloc[x,4])):
        votes[15] += int(df.iloc[x,12])
        y = 15
    if re.search("017", str(df.iloc[x,4])):
        votes[16] += int(df.iloc[x,12])
        y = 16
    if re.search("018", str(df.iloc[x,4])):
        votes[17] += int(df.iloc[x,12])
        y = 17
    if re.search("019", str(df.iloc[x,4])):
        votes[18] += int(df.iloc[x,12])
        y = 18
    if re.search("020", str(df.iloc[x,4])):
        votes[19] += int(df.iloc[x,12])
        y = 19
    if re.search("021", str(df.iloc[x,4])):
        votes[20] += int(df.iloc[x,12])
        y = 20
    if re.search("022", str(df.iloc[x,4])):
        votes[21] += int(df.iloc[x,12])
        y = 21
    if re.search("023", str(df.iloc[x,4])):
        votes[22] += int(df.iloc[x,12])
        y = 22
    if re.search("024", str(df.iloc[x,4])):
        votes[23] += int(df.iloc[x,12])
        y = 23
    if re.search("025", str(df.iloc[x,4])):
        votes[24] += int(df.iloc[x,12])
        y = 24
    if re.search("026", str(df.iloc[x,4])):
        votes[25] += int(df.iloc[x,12])
        y = 25
    if re.search("027", str(df.iloc[x,4])):
        votes[26] += int(df.iloc[x,12])
        y = 26
    if re.search("028", str(df.iloc[x,4])):
        votes[27] += int(df.iloc[x,12])
        y = 27
    if re.search("029", str(df.iloc[x,4])):
        votes[28] += int(df.iloc[x,12])
        y = 28
    if re.search("030", str(df.iloc[x,4])):
        votes[29] += int(df.iloc[x,12])
        y = 29
    if re.search("031", str(df.iloc[x,4])):
        votes[30] += int(df.iloc[x,12])
        y = 30
    if re.search("032", str(df.iloc[x,4])):
        votes[31] += int(df.iloc[x,12])
        y = 31
    if re.search("033", str(df.iloc[x,4])):
        votes[32] += int(df.iloc[x,12])
        y = 32
    if re.search("034", str(df.iloc[x,4])):
        votes[33] += int(df.iloc[x,12])
        y = 33
    if re.search("035", str(df.iloc[x,4])):
        votes[34] += int(df.iloc[x,12])
        y = 34
    if re.search("036", str(df.iloc[x,4])):
        votes[35] += int(df.iloc[x,12])
        y = 35
    if re.search("037", str(df.iloc[x,4])):
        votes[36] += int(df.iloc[x,12])
        y = 36
    if re.search("038", str(df.iloc[x,4])):
        votes[37] += int(df.iloc[x,12])
        y = 37
    if re.search("039", str(df.iloc[x,4])):
        votes[38] += int(df.iloc[x,12])
        y = 38
    if re.search("040", str(df.iloc[x,4])):
        votes[39] += int(df.iloc[x,12])
        y = 39
    if re.search("041", str(df.iloc[x,4])):
        votes[40] += int(df.iloc[x,12])
        y = 40
    if re.search("042", str(df.iloc[x,4])):
        votes[41] += int(df.iloc[x,12])
        y = 41
    if re.search("043", str(df.iloc[x,4])):
        votes[42] += int(df.iloc[x,12])
        y = 42
    if re.search("044", str(df.iloc[x,4])):
        votes[43] += int(df.iloc[x,12])
        y = 43
    if re.search("044", str(df.iloc[x,4])):
        votes[43] += int(df.iloc[x,12])
        y = 43
    if re.search("045", str(df.iloc[x,4])):
        votes[44] += int(df.iloc[x,12])
        y = 44
    if re.search("046", str(df.iloc[x,4])):
        votes[45] += int(df.iloc[x,12])
        y = 45
    if re.search("047", str(df.iloc[x,4])):
        votes[46] += int(df.iloc[x,12])
        y = 46
    if re.search("048", str(df.iloc[x,4])):
        votes[47] += int(df.iloc[x,12])
        y = 47
    if re.search("049", str(df.iloc[x,4])):
        votes[48] += int(df.iloc[x,12])
        y = 48
    if re.search("050", str(df.iloc[x,4])):
        votes[49] += int(df.iloc[x,12])
        y = 49
    if re.search("051", str(df.iloc[x,4])):
        votes[50] += int(df.iloc[x,12])
        y = 50
    if re.search("052", str(df.iloc[x,4])):
        votes[51] += int(df.iloc[x,12])
        y = 51
    if re.search("053", str(df.iloc[x,4])):
        votes[52] += int(df.iloc[x,12])
        y = 52
    if re.search("054", str(df.iloc[x,4])):
        votes[53] += int(df.iloc[x,12])
        y = 53
    if re.search("055", str(df.iloc[x,4])):
        votes[54] += int(df.iloc[x,12])
        y = 54
    if re.search("056", str(df.iloc[x,4])):
        votes[55] += int(df.iloc[x,12])
        y = 55
    if re.search("057", str(df.iloc[x,4])):
        votes[56] += int(df.iloc[x,12])
        y = 56
    if re.search("058", str(df.iloc[x,4])):
        votes[57] += int(df.iloc[x,12])
        y = 57
    if re.search("059", str(df.iloc[x,4])):
        votes[58] += int(df.iloc[x,12])
        y = 58
    if re.search("060", str(df.iloc[x,4])):
        votes[59] += int(df.iloc[x,12])
        y = 59
    if re.search("061", str(df.iloc[x,4])):
        votes[60] += int(df.iloc[x,12])
        y = 60
    if re.search("062", str(df.iloc[x,4])):
        votes[61] += int(df.iloc[x,12])
        y = 61
    if re.search("063", str(df.iloc[x,4])):
        votes[62] += int(df.iloc[x,12])
        y = 62
    if re.search("064", str(df.iloc[x,4])):
        votes[63] += int(df.iloc[x,12])
        y = 63
    if re.search("065", str(df.iloc[x,4])):
        votes[64] += int(df.iloc[x,12])
        y = 64
    if re.search("066", str(df.iloc[x,4])):
        votes[65] += int(df.iloc[x,12])
        y = 65
    if re.search("067", str(df.iloc[x,4])):
        votes[66] += int(df.iloc[x,12])
        y = 66
    if re.search("068", str(df.iloc[x,4])):
        votes[67] += int(df.iloc[x,12])
        y = 67
    if re.search("069", str(df.iloc[x,4])):
        votes[68] += int(df.iloc[x,12])
        y = 68
    if re.search("070", str(df.iloc[x,4])):
        votes[69] += int(df.iloc[x,12])
        y = 69
    if re.search("071", str(df.iloc[x,4])):
        votes[70] += int(df.iloc[x,12])
        y = 70
    if re.search("072", str(df.iloc[x,4])):
        votes[71] += int(df.iloc[x,12])
        y = 71
    if re.search("073", str(df.iloc[x,4])):
        votes[72] += int(df.iloc[x,12])
        y = 72
    if re.search("074", str(df.iloc[x,4])):
        votes[73] += int(df.iloc[x,12])
        y = 73
    if re.search("075", str(df.iloc[x,4])):
        votes[74] += int(df.iloc[x,12])
        y = 74
    if re.search("076", str(df.iloc[x,4])):
        votes[75] += int(df.iloc[x,12])
        y = 75
    if re.search("077", str(df.iloc[x,4])):
        votes[76] += int(df.iloc[x,12])
        y = 76
    if re.search("078", str(df.iloc[x,4])):
        votes[77] += int(df.iloc[x,12])
        y = 77
    if re.search("079", str(df.iloc[x,4])):
        votes[78] += int(df.iloc[x,12])
        y = 78
    if re.search("080", str(df.iloc[x,4])):
        votes[79] += int(df.iloc[x,12])
        y = 79
    if re.search("081", str(df.iloc[x,4])):
        votes[80] += int(df.iloc[x,12])
        y = 80
    if re.search("082", str(df.iloc[x,4])):
        votes[81] += int(df.iloc[x,12])
        y = 81
    if re.search("083", str(df.iloc[x,4])):
        votes[82] += int(df.iloc[x,12])
        y = 82
    if re.search("084", str(df.iloc[x,4])):
        votes[83] += int(df.iloc[x,12])
        y = 83
    if re.search("085", str(df.iloc[x,4])):
        votes[84] += int(df.iloc[x,12])
        y = 84
    if re.search("086", str(df.iloc[x,4])):
        votes[85] += int(df.iloc[x,12])
        y = 85
    if re.search("087", str(df.iloc[x,4])):
        votes[86] += int(df.iloc[x,12])
        y = 86
    if re.search("088", str(df.iloc[x,4])):
        votes[87] += int(df.iloc[x,12])
        y = 87
    if re.search("089", str(df.iloc[x,4])):
        votes[88] += int(df.iloc[x,12])
        y = 88
    if re.search("090", str(df.iloc[x,4])):
        votes[89] += int(df.iloc[x,12])
        y = 89
    if re.search("091", str(df.iloc[x,4])):
        votes[90] += int(df.iloc[x,12])
        y = 90
    if re.search("092", str(df.iloc[x,4])):
        votes[91] += int(df.iloc[x,12])
        y = 91
    if re.search("093", str(df.iloc[x,4])):
        votes[92] += int(df.iloc[x,12])
        y = 92
    if re.search("094", str(df.iloc[x,4])):
        votes[93] += int(df.iloc[x,12])
        y = 93
    if re.search("095", str(df.iloc[x,4])):
        votes[94] += int(df.iloc[x,12])
        y = 94
    if re.search("096", str(df.iloc[x,4])):
        votes[95] += int(df.iloc[x,12])
        y = 95
    if re.search("097", str(df.iloc[x,4])):
        votes[96] += int(df.iloc[x,12])
        y = 96
    if re.search("098", str(df.iloc[x,4])):
        votes[97] += int(df.iloc[x,12])
        y = 97
    if re.search("099", str(df.iloc[x,4])):
        votes[98] += int(df.iloc[x,12])
        y = 98
    if re.search("100", str(df.iloc[x,4])):
        votes[99] += int(df.iloc[x,12])
        y = 99
    if re.search("101", str(df.iloc[x,4])):
        votes[100] += int(df.iloc[x,12])
        y = 100
    if re.search("102", str(df.iloc[x,4])):
        votes[101] += int(df.iloc[x,12])
        y = 101
    if re.search("103", str(df.iloc[x,4])):
        votes[102] += int(df.iloc[x,12])
        y = 102
    if re.search("104", str(df.iloc[x,4])):
        votes[103] += int(df.iloc[x,12])
        y = 103
    if re.search("105", str(df.iloc[x,4])):
        votes[104] += int(df.iloc[x,12])
        y = 104
    if re.search("106", str(df.iloc[x,4])):
        votes[105] += int(df.iloc[x,12])
        y = 105
    if re.search("107", str(df.iloc[x,4])):
        votes[106] += int(df.iloc[x,12])
        y = 106
    if re.search("108", str(df.iloc[x,4])):
        votes[107] += int(df.iloc[x,12])
        y = 107
    if re.search("109", str(df.iloc[x,4])):
        votes[108] += int(df.iloc[x,12])
        y = 108
    if re.search("110", str(df.iloc[x,4])):
        votes[109] += int(df.iloc[x,12])
        y = 109
    if re.search("111", str(df.iloc[x,4])):
        votes[110] += int(df.iloc[x,12])
        y = 110
    if re.search("112", str(df.iloc[x,4])):
        votes[111] += int(df.iloc[x,12])
        y = 111
    if re.search("113", str(df.iloc[x,4])):
        votes[112] += int(df.iloc[x,12])
        y = 112
    if re.search("114", str(df.iloc[x,4])):
        votes[113] += int(df.iloc[x,12])
        y = 113
    if re.search("115", str(df.iloc[x,4])):
        votes[114] += int(df.iloc[x,12])
        y = 114
    if re.search("116", str(df.iloc[x,4])):
        votes[115] += int(df.iloc[x,12])
        y = 115
    if re.search("117", str(df.iloc[x,4])):
        votes[116] += int(df.iloc[x,12])
        y = 116
    if re.search("118", str(df.iloc[x,4])):
        votes[117] += int(df.iloc[x,12])
        y = 117
    if re.search("119", str(df.iloc[x,4])):
        votes[118] += int(df.iloc[x,12])
        y = 118
    if re.search("120", str(df.iloc[x,4])):
        votes[119] += int(df.iloc[x,12])
        y = 119


df = pd.read_csv('https://query.data.world/s/xxuvyisnx5y3saqqkd3gdgass5v6od', index_col = 0)
df.sort_values(by=['contest_name'], inplace = True)
df.sort_values(by=['county'], inplace = True)

house = [0] * 120
for i in range(120):
    house[i] = i + 1

total_votes = [0] * 120
grandTotal = [0] * 120
a = 0 #repub iterator
b = 0 #total iterator

d = {}
d = dict()
e = {}
e = dict()

#intial county (ALAMANCE)
for x in range(49607):
    if re.search("NC HOUSE", str(df.iloc[x,4])):
        findHouseNum(df, grandTotal, x, b)

        if re.search("REP", str(df.iloc[x,6])): #repeat for rep setion
            findHouseNum(df, total_votes, x, b)


for i in range(120):
    e.update({house[i] : grandTotal[i]})
    d.update({house[i] : total_votes[i]})


with open('out.csv', 'w') as csvfile:
    writer = csv.DictWriter(csvfile, d.keys())
    writer.writeheader()
    writer.writerow(d)
    writer.writerow(e)

csvfile.close()
